# This was modified as of version 0.5.0
[bar]
scale = 1.0

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "window-title",
]
center = [
    "clock",
    "notifications",
]
right = [
    "network",
    "bluetooth",
    "volume",
    "battery",
]

[modules.dashboard]
dropdown-reboot-command = "loginctl reboot"
dropdown-poweroff-command = "loginctl poweroff"

[modules.notifications]
popup-position = "top-center"

[modules.volume]
border-color = "green"
icon-bg-color = "green"
label-color = "green"

[modules.window-title]
label-max-length = 20

[wallpaper]
engine-enabled = false

