# This was modified as of version 0.5.0
[general]
font-sans = "Inter"
font-mono = "CaskaydiaMono Nerd Font"
tearing-mode = false

[bar]
location = "top"
exclusive = true
layer = "top"
shadow = "none"
button-variant = "block-prefix"
dropdown-shadow = false

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "window-title",
]
center = [
    "hyprsunset",
    "clock",
    "notifications",
]
right = [
    "network",
    "bluetooth",
    "volume",
    "battery",
]

[styling]
theme-provider = "wayle"

[modules.clock]
format = "%d-%m-%Y %H:%M:%S"
right-click = ""
dropdown-show-seconds = true

# If you're on non-systemd distros, replace systemctl with loginctl
[modules.dashboard]
border-color = "yellow"
icon-color = "auto"
icon-bg-color = "yellow"
dropdown-lock-command = "loginctl lock-session"
dropdown-logout-command = "loginctl terminate-session $XDG_SESSION_ID"
dropdown-reboot-command = "loginctl reboot"
dropdown-poweroff-command = "loginctl poweroff"

[modules.notifications]
popup-position = "top-center"

[modules.volume]
border-color = "green"
icon-bg-color = "green"
label-color = "green"

[modules.weather]
time-format = "24h"

[modules.window-title]
label-max-length = 20

[osd]
enabled = true
duration = 1000
border = false

[wallpaper]
engine-enabled = false
