# Main Configuration
[main]
font=CaskaydiaMono Nerd Font:size=10
bold-font=CaskaydiaMono Nerd Font:bold:size=10
italic-font=CaskaydiaMono Nerd Font:italic:size=10
bold-italic-font=CaskaydiaMono Nerd Font:bold:italic:size=10

[cursor]
style=beam

# Nord Theme
[colors-dark]
alpha=0.8

foreground=d8dee9
background=2e3440
selection-foreground=000000
selection-background=fffacd

cursor=2e3440 81a1c1
urls=0087bd

# Black
regular0=3b4252
bright0=4c566a

# Red
regular1=bf616a
bright1=bf616a

# Green
regular2=a3be8c
bright2=a3be8c

# Yellow
regular3=ebcb8b
bright3=ebcb8b

# Blue
regular4=81a1c1
bright4=81a1c1

# Magenta
regular5=b48ead
bright5=b48ead

# Cyan
regular6=88c0d0
bright6=8fbcbb

# White
regular7=e5e9f0
bright7=eceff4
