# This was modified as of version 1.27.0
[main]
font=CaskaydiaMono Nerd Font:size=12
font-bold=CaskaydiaMono Nerd Font:bold:size=12
font-italic=CaskaydiaMono Nerd Font:italic:size=12
font-bold-italic=CaskaydiaMono Nerd Font:bold:italic:size=12

# Theme
[main]
include=~/.config/foot/theme.ini

[colors-dark]
alpha=0.8

[cursor]
style=beam
