-- https://wiki.hypr.land/Configuring/Start/
require("parts.monitors")
require("parts.env")
require("parts.startup")
require("parts.binds")
require("parts.gestures")
require("parts.rules")
require("parts.main")
require("parts.animations")
require("parts.plugins")
