# This was modified as of version 0.9.5
source = ~/.config/hypr/parts/theme.conf

background {
    path = screenshot
    blur_size = 5
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.5
    vibrancy_darkness = 0.5
}

general {
    hide_cursor = true
    ignore_empty_input = true
}

input-field {
    size = 300, 50
    outline_thickness = 5
    dots_size = 0.25
    dots_floating = 0.35
    dots_center = true
    outer_color = $outer
    inner_color = $inner
    check_color = $check
    font_color = $font
    fade_on_empty = false
}
