# General Looks
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 5
    resize_on_border = false

    layout = dwindle

    col.active_border = rgb(115,121,148)
    col.inactive_border = rgb(35,38,52)
    
    allow_tearing = false # Do not change.
}

# Decoration
decoration {
    rounding = 0 # I like boxes.
    rounding_power = 0 # I support box supremacy.

    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    blur {
        enabled = false # Happy iGPU noises.
    }

    shadow {
        enabled = false # I do not need it.
    }
}

# Animations
animation {
    enabled = false # Just like Sway.
}

# Layout
dwindle {
    pseudotile = false
    preserve_split = true
}
